<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 6.0.2 (Python 3.11.3 on win32)" generated="20230724 12:51:25.462" rpa="false" schemaversion="3">
<suite id="s1" name="Home" source="D:\Automatizacion\Netflix_RobotFramework\Netflix\specs\home.robot">
<test id="s1-t1" name="Scenario:Home page Netflix" line="14">
<kw name="Given I am in the Netflix page">
<kw name=" Open Netflix" library="home-sd">
<kw name="prueba cguzman">
<msg timestamp="20230724 12:51:25.822" level="FAIL">No keyword with name 'prueba cguzman' found.</msg>
<status status="FAIL" starttime="20230724 12:51:25.822" endtime="20230724 12:51:25.822"/>
</kw>
<status status="FAIL" starttime="20230724 12:51:25.815" endtime="20230724 12:51:25.823"/>
</kw>
<kw name="Verify I am in the home page" library="home-sd">
<status status="NOT RUN" starttime="20230724 12:51:25.823" endtime="20230724 12:51:25.823"/>
</kw>
<kw name="I click on Login button" library="home-sd">
<status status="NOT RUN" starttime="20230724 12:51:25.823" endtime="20230724 12:51:25.823"/>
</kw>
<status status="FAIL" starttime="20230724 12:51:25.815" endtime="20230724 12:51:25.823"/>
</kw>
<kw name="When I am filling the Sign data">
<status status="NOT RUN" starttime="20230724 12:51:25.824" endtime="20230724 12:51:25.824"/>
</kw>
<kw name="Then clicking on Sign in button">
<status status="NOT RUN" starttime="20230724 12:51:25.824" endtime="20230724 12:51:25.824"/>
</kw>
<status status="FAIL" starttime="20230724 12:51:25.814" endtime="20230724 12:51:25.825">No keyword with name 'prueba cguzman' found.</status>
</test>
<status status="FAIL" starttime="20230724 12:51:25.465" endtime="20230724 12:51:25.830"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Home">Home</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20230724 12:51:25.775" level="ERROR">Error in file 'D:\Automatizacion\Netflix_RobotFramework\Netflix\specs\home.robot' on line 3: Importing library 'ExtendedSelenium2Library' failed: ModuleNotFoundError: No module named 'ExtendedSelenium2Library'
Traceback (most recent call last):
  None
PYTHONPATH:
  C:\Users\cathe\AppData\Local\Programs\Python\Python311\Scripts\robot.exe
  C:\Users\cathe\AppData\Local\Programs\Python\Python311\python311.zip
  C:\Users\cathe\AppData\Local\Programs\Python\Python311\DLLs
  C:\Users\cathe\AppData\Local\Programs\Python\Python311\Lib
  C:\Users\cathe\AppData\Local\Programs\Python\Python311
  C:\Users\cathe\AppData\Local\Programs\Python\Python311\Lib\site-packages</msg>
<msg timestamp="20230724 12:51:25.788" level="ERROR">Error in file 'D:\Automatizacion\Netflix_RobotFramework\Netflix\stepdefinitions\home-sd.robot' on line 3: Importing library 'D:\Automatizacion\Netflix_RobotFramework\Netflix\resources\inicio.py' failed: ModuleNotFoundError: No module named 'webdriver_manager'
Traceback (most recent call last):
  File "D:\Automatizacion\Netflix_RobotFramework\Netflix\resources\inicio.py", line 4, in &lt;module&gt;
    from webdriver_manager.chrome import ChromeDriverManager
PYTHONPATH:
  D:\Automatizacion\Netflix_RobotFramework\Netflix\resources
  C:\Users\cathe\AppData\Local\Programs\Python\Python311\Scripts\robot.exe
  C:\Users\cathe\AppData\Local\Programs\Python\Python311\python311.zip
  C:\Users\cathe\AppData\Local\Programs\Python\Python311\DLLs
  C:\Users\cathe\AppData\Local\Programs\Python\Python311\Lib
  C:\Users\cathe\AppData\Local\Programs\Python\Python311
  C:\Users\cathe\AppData\Local\Programs\Python\Python311\Lib\site-packages</msg>
</errors>
</robot>
